[package]
name = "quadratic-rust-shared"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aws-config = { version= "1.1.1", features = ["behavior-version-latest"] }
aws-sdk-s3 = {version = "1.12.0", features = ["behavior-version-latest", "rt-tokio"] }
chrono = "0.4.31"
futures-util = "0.3.30"
jsonwebtoken = "9.2.0"
redis = { version = "0.24.0", features = ["tokio-comp"] }
reqwest = { version = "0.11.22", features = ["json", "serde_json"] }
serde = { version = "1.0.193", features = ["derive"] }
serde_json = "1.0.108"
strum = "0.25.0"
strum_macros = "0.25.3"
thiserror = "1.0.51"
tokio = { version = "1.34.0", features = ["full"] }
uuid = { version = "1.6.1", features = ["serde", "v4"] }

[dev-dependencies]
